logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  rabbitmq:
    host: rabbitmq


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /oauth/**
      url: http://localhost:9181
      stripPrefix: false
      sensitiveHeaders:

    onboarding-service:
      path: /onboarding/**
      serviceId: http://localhost:9182
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 9180
