logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://registry:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /oauth/**
      url: http://localhost:9191
      stripPrefix: false
      sensitiveHeaders:

    onboarding-service:
      path: /onboarding/**
      serviceId: http://localhost:8192
      stripPrefix: false
      sensitiveHeaders:

#    account-service:
#      path: /accounts/**
#      serviceId: account-service
#      stripPrefix: false
#      sensitiveHeaders:
#
#    statistics-service:
#      path: /statistics/**
#      serviceId: statistics-service
#      stripPrefix: false
#      sensitiveHeaders:
#
#    notification-service:
#      path: /notifications/**
#      serviceId: notification-service
#      stripPrefix: false
#      sensitiveHeaders:

server:
  port: 4000
