server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amit---kumar/config-store
          search-paths:
            - service/onboarding-service*
            - service/search-service*
            - service/eureka-service*
            - service/auth-service*
            - service/gateway-service*
  application:
    name: config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost